site_name: WgpArch Sway Config
site_url: https://wgparch.gitlab.io/sway/
theme:
  name: material
  palette:
    primary: blue grey
    accent: light blue
  features:
    - navigation.tabs
    - navigation.expand
nav:
  - Home: index.md
  - Installation: installation.md
  - Bars:
    - Waybar: waybar.md
    - EWW: eww.md
  - Keybinds: keybinds.md
  - Look & Feel: theming.md
  - Gallery: gallery.md
